# Generated by Django 2.0.7 on 2018-08-08 01:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=250)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be enteredin the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('school', models.CharField(max_length=250)),
                ('graduation_date', models.DateField()),
                ('major', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('dietary_restrictions', models.IntegerField(choices=[(0, 'None'), (1, 'Kosher'), (2, 'Gluten-Free'), (3, 'Vegan'), (4, 'Vegetarian')], default=0)),
                ('allergies', models.TextField()),
                ('github', models.CharField(max_length=250)),
                ('linkedin', models.CharField(max_length=250)),
                ('personal_website', models.CharField(max_length=250)),
                ('resume', models.CharField(max_length=250)),
                ('short_answer', models.TextField()),
                ('gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Other')], default=0)),
                ('ethnicity', models.IntegerField(choices=[(0, 'American Indian or Alaska Native'), (1, 'Asian'), (2, 'Black or African American'), (3, 'Hispanic or Latino'), (4, 'Native Hawaiian or Other Pacific Islander'), (5, 'White'), (6, 'Other')], default=0)),
                ('anything_else', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
