# Generated by Django 2.0.7 on 2018-08-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=250)),
                ('t_shirt', models.IntegerField(choices=[(0, 'x-small'), (1, 'small'), (2, 'medium'), (3, 'large'), (4, 'x-large')], default=0)),
                ('dob', models.DateField()),
                ('resume', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
