# Generated by Django 2.1 on 2018-08-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_eighteen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='short_answer',
            field=models.TextField(default=False),
        ),
    ]
