# Generated by Django 2.1 on 2018-08-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180808_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='short_answer',
            field=models.TextField(),
        ),
    ]
