# Generated by Django 2.1 on 2018-08-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to=''),
        ),
    ]
