# Generated by Django 2.1 on 2018-08-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20180810_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.CharField(max_length=250),
        ),
    ]
