# Generated by Django 2.1 on 2018-08-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180816_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='resume/'),
        ),
    ]
